trigger:
- none

stages:
- stage: Testing
  jobs:
  - job: Testing
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: PowerShell@2
      displayName: 'Install Chef WS'
      inputs:
        targetType: 'inline'
        script: '.{ iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel current -project chef-workstation'
      env:
        CHEF_LICENSE: accept
    - task: PowerShell@2
      displayName: 'Check cookbook with cookstyle'
      inputs:
        targetType: 'inline'
        workingDirectory: $(Build.SourcesDirectory)
        script: 'cookstyle ../'
      env:
        CHEF_LICENSE: accept
    # - task: PowerShell@2
    #   displayName: 'Run chef localy'
    #   inputs:
    #     targetType: 'inline'
    #     workingDirectory: $(Build.SourcesDirectory)
    #     script: 'here-the-magic-happens'
    #   env:
    #     CHEF_LICENSE: accept
